### ISSUE TITLE
问题较多，运行的时候保存 5 18 60 等多个错误代码

### ISSUE THREAD

**Issue by lukemin** [sec-an/Better-Auto-XXQG#1]
最好能加上导入log的功能，方便反馈。

**Comment by sec-an** [comment]
> 最好能加上导入log的功能，方便反馈。

客户端UI界面能够正常加载？UI界面返回一次就是默认的日志模块~

**Comment by lukemin** [comment]
默认日志，复制非常的不方便。

**Comment by sec-an** [comment]
> 默认日志，复制非常的不方便。

好的，后续在UI界面进行更新，加入日志功能
