### ISSUE TITLE
希望添加多账号学习功能

### ISSUE THREAD

**Issue by shuaiqingm** [sec-an/Better-Auto-XXQG#17]
希望添加多账号学习功能，之前[auto-xxqg]的就带多账号功能，我这还有他的代码。

**Comment by sec-an** [comment]
> 希望添加多账号学习功能，之前[auto-xxqg]的就带多账号功能，我这还有他的代码。

可以给个链接或分享一下代码吗

**Comment by njuws** [comment]
https://github.com/auto-xxqg/auto-xxqg/releases这里可以直接下载多账号的那个源码。

**Comment by shuaiqingm** [comment]
上面这个里面有的

**Comment by sec-an** [comment]
> https://github.com/auto-xxqg/auto-xxqg/releases
> 这里可以直接下载多账号的那个源码。

好的，有空参考一下

**Comment by sec-an** [comment]
最新版本选择脚本天天向上Pro，应该可以实现，但是没有测试

**Comment by shuaiqingm** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
