### ISSUE TITLE
内置OCR闪退无法使用

### ISSUE THREAD

**Issue by 59864299** [sec-an/Better-Auto-XXQG#25]
小米手机选择内置OCR开启无障碍后闪退，什么时候可以出一个OCR插件的

**Comment by CaoYK1225** [comment]
我也遇到过这样的情况。有时候清理数据、取消root权限后就能恢复正常。但不知道这操作是不是每次都有效。

**Comment by sec-an** [comment]
最新版选择天天向上Pro可以用插件，但是没有测试
