### ISSUE TITLE
孤儿作者你好

### ISSUE THREAD

**Issue by tongcheung0218** [sec-an/Better-Auto-XXQG#29]
盗取别人源码来这里找存在感，怎么会有你这种脑残小偷二百五呢？装你妈逼的coder啊？有本事实名吗，狗杂碎

**Comment by xiamu521** [comment]
取其精华去其糟粕，这个软件多好用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月30日(星期三) 晚上11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [sec-an/Better-Auto-XXQG] 孤儿作者你好 (Issue #29)





 
盗取别人源码来这里找存在感，怎么会有你这种脑残小偷二百五呢？装你妈逼的coder啊？有本事实名吗，狗杂碎

**Comment by sec-an** [comment]
# **声明**

1. 本人的确在[Twelve-blog / Study_hamibot](https://github.com/Twelve-blog/Study_hamibot)项目开源前获取了相关源代码，当时Study作者尚未开源，因此无法Fork，只能新建仓库（见2）并在此基础上进行不同平台的代码移植和简要修改。
2. 本项目最开始的主脚本与[Twelve-blog / Study_hamibot](https://github.com/Twelve-blog/Study_hamibot)没有任何关系，是参考了别的项目所写，因此Readme文件中存在“参考项目”的Title，修改主脚本后将相关链接变更为[Study](https://hamibot.com/marketplace/1Kw2X?invite=ONTRWIBaZqdBWuDk6DNzT7rt)，基于时间原因暂时只进行了不同平台的代码移植和适配，自行编写了简单的UI界面，还没有进一步的修改和完善。
4. 所谓“窃取”行为，存在一个必要的前提：Study项目作者在[Hamibot脚本市场](https://hamibot.com/marketplace/1Kw2X?invite=ONTRWIBaZqdBWuDk6DNzT7rt)和后期开源的[Twelve-blog / Study_hamibot](https://github.com/Twelve-blog/Study_hamibot)显著位置处均标明其项目修改来源于：[LazyStudy](https://github.com/lolisaikou/LazyStudy)，而LazyStudy采用的是[GPL-2.0 License](https://github.com/lolisaikou/LazyStudy/blob/master/LICENSE)，根据相关开源协议，Study项目作者应在基于LazyStudy修改并于Hamibot脚本市场进行分发时开源，并采用同样的[GPL-2.0 License](https://github.com/lolisaikou/LazyStudy/blob/master/LICENSE)协议，而在Hamibot脚本市场使用[Study](https://hamibot.com/marketplace/1Kw2X?invite=ONTRWIBaZqdBWuDk6DNzT7rt)脚本的所有用户，均有获取源码的权利。
5. 根据[Twelve-blog / Study_hamibot](https://github.com/Twelve-blog/Study_hamibot)开源后的Readme文件，本项目已在最后将“参考项目”修改为“主脚本修改自”，并修改了本项目先前采用的Apache2.0开源协议为更加准确的[GPL-2.0 License](https://github.com/lolisaikou/LazyStudy/blob/master/LICENSE)，以遵守LazyStudy所采用协议的要求，且本项目没有商业化、盈利或接受赞助的打算。
6. 请可以联系到Study项目作者的朋友，及时提醒ta修改其[Twelve-blog / Study_hamibot](https://github.com/Twelve-blog/Study_hamibot)开源项目的相关协议为[GPL-2.0 License](https://github.com/lolisaikou/LazyStudy/blob/master/LICENSE)，遵守开源社区的相关规定。

**Comment by tongcheung0218** [comment]
最简单的道理，Study代码完全是私密链接且未公开，你是如何过去到其代码的？别告诉我这都不算剽窃

**Comment by tongcheung0218** [comment]
最简单的道理，Study代码完全是私密链接且未公开，你是如何获取到其代码的？别告诉我这都不算剽窃
