### ISSUE TITLE
双人对战出现异常提示，要求滑动验证

### ISSUE THREAD

**Issue by sxuway** [sec-an/Better-Auto-XXQG#32]
是不是被监测到了

**Comment by xiamu521** [comment]
这个好像是官方增加的验证




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sec-an/Better-Auto-XXQG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 上午10:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[sec-an/Better-Auto-XXQG] 双人对战出现异常提示，要求滑动验证 (Issue #32)





 
是不是被监测到了

**Comment by sec-an** [comment]
已修复
