### ISSUE TITLE
视频学习无法得满分

### ISSUE THREAD

**Issue by youjumenkou** [sec-an/Better-Auto-XXQG#35]
因为百灵视频里不再支持下滑刷新视频，所以脚本下滑刷新后仍然浏览之前看过的视频，无法得满分，电视视频学习也无法的满分，求帮助。

**Comment by staoran** [comment]
是不是要把秒数调大一点呀

**Comment by youjumenkou** [comment]
自己手动刷新试了一下 也是不更新的

**Comment by youjumenkou** [comment]
能调整验证时间的是新版吗？老版本不自动更新吗？
