### ISSUE TITLE
无法运行。

### ISSUE THREAD

**Issue by lukemin** [sec-an/Better-Auto-XXQG#4]
17:27:09.265/D: { '登录': [ '1', index: 2, input: '已获1分/每日上限1分' ],
  '我要选读文章': [ '12', index: 2, input: '已获12分/每日上限12分' ],
  '视听学习': [ '3', index: 2, input: '已获3分/每日上限6分' ],
  '视听学习时长': [ '6', index: 2, input: '已获6分/每日上限6分' ],
  '每日答题': [ '0', index: 2, input: '已获0分/每日上限5分' ],
  '每周答题': [ '0', index: 2, input: '已获0分/每日上限5分' ],
  '专项答题': [ '0', index: 2, input: '已获0分/每日上限10分' ],
  '挑战答题': [ '0', index: 2, input: '已获0分/每日上限6分' ],
  '四人赛': [ '0', index: 2, input: '已获0分/每日上限5分' ],
  '双人对战': [ '0', index: 2, input: '已获0分/每日上限2分' ],
  '订阅': [ '0', index: 2, input: '已获0分/每日上限2分' ],
  '分享': [ '1', index: 2, input: '已获1分/每日上限1分' ],
  '发表观点': [ '0', index: 2, input: '已获0分/每日上限1分' ],
  '本地频道': [ '1', index: 2, input: '已获1分/每日上限1分' ],
  '强国运动': [ '0', index: 2, input: '已获0分/每周上限2分' ] }
![微信图片_20220216173027](https://user-images.githubusercontent.com/12003375/154235595-2485a384-c1fa-4a17-9660-0556cf5b8813.jpg)

卡住了

**Comment by sec-an** [comment]
> 17:27:09.265/D: { '登录': [ '1', index: 2, input: '已获1分/每日上限1分' ], '我要选读文章': [ '12', index: 2, input: '已获12分/每日上限12分' ], '视听学习': [ '3', index: 2, input: '已获3分/每日上限6分' ], '视听学习时长': [ '6', index: 2, input: '已获6分/每日上限6分' ], '每日答题': [ '0', index: 2, input: '已获0分/每日上限5分' ], '每周答题': [ '0', index: 2, input: '已获0分/每日上限5分' ], '专项答题': [ '0', index: 2, input: '已获0分/每日上限10分' ], '挑战答题': [ '0', index: 2, input: '已获0分/每日上限6分' ], '四人赛': [ '0', index: 2, input: '已获0分/每日上限5分' ], '双人对战': [ '0', index: 2, input: '已获0分/每日上限2分' ], '订阅': [ '0', index: 2, input: '已获0分/每日上限2分' ], '分享': [ '1', index: 2, input: '已获1分/每日上限1分' ], '发表观点': [ '0', index: 2, input: '已获0分/每日上限1分' ], '本地频道': [ '1', index: 2, input: '已获1分/每日上限1分' ], '强国运动': [ '0', index: 2, input: '已获0分/每周上限2分' ] } ![微信图片_20220216173027](https://user-images.githubusercontent.com/12003375/154235595-2485a384-c1fa-4a17-9660-0556cf5b8813.jpg)
> 
> 卡住了

好像没有报错信息…关闭所有程序重新运行试试？

**Comment by lukemin** [comment]
不自动观看视频，就在这个界面不动了

**Comment by sec-an** [comment]
> 不自动观看视频，就在这个界面不动了

从左下角的悬浮窗看好像开了不止一个进程，可能进程之间有冲突了

**Comment by lukemin** [comment]
BUG还是很多。
文章阅读是碰到播放音频的文章时会卡住。
![81f2d5942f4826bd062e388545a6b85](https://user-images.githubusercontent.com/12003375/154382922-dffced4e-5c2d-4e94-9cb8-cc5d52fe8d64.jpg)
答题界面进入之后就保存退出了。
![81f2d5942f4826bd062e388545a6b85](https://user-images.githubusercontent.com/12003375/154383002-595c4d5a-9de7-4eae-8a06-39018bb1e181.jpg)
08:06:59.427/E: TypeError: Cannot call method "click" of null (强国助手.js#190)
TypeError: Cannot call method "click" of null
    at 强国助手.js:190:0

**Comment by haowen2000** [comment]
确实无法播放视频，卡住

**Comment by sec-an** [comment]
> BUG还是很多。 文章阅读是碰到播放音频的文章时会卡住。 ![81f2d5942f4826bd062e388545a6b85](https://user-images.githubusercontent.com/12003375/154382922-dffced4e-5c2d-4e94-9cb8-cc5d52fe8d64.jpg) 答题界面进入之后就保存退出了。 ![4330f4a5724e980d9cc8281673967ef](https://user-images.githubusercontent.com/12003375/154383083-7cf40453-aa4e-4d20-b3ec-466d2de8a1c3.jpg) 08:06:59.427/E: TypeError: Cannot call method "click" of null (强国助手.js#190) TypeError: Cannot call method "click" of null at 强国助手.js:190:0

前一个是bug，后一个可能和机型有关，建议将默认延时设置为2秒试试，之后我也会针对这个做一下优化

**Comment by sec-an** [comment]
> 确实无法播放视频，卡住

可以描述稍微具体一些吗？是在百灵页看视频的时候卡住，还是读文章的时候遇到有视频的文章卡住？

**Comment by lukemin** [comment]
百灵视频有时候进入视频列表页后，不点击播放，一直呆在视频列表界面。
有些音视频文章，进入后就不继续了。

**Comment by sec-an** [comment]
已修复
