### ISSUE TITLE
使用新版的autox.js，导入源码main，然后运行就可以在miui13使用了

### ISSUE THREAD

**Issue by boy5260** [sec-an/Better-Auto-XXQG#44]
RT，今天测试的，正常使用。希望能稳下来。

**Comment by boy5260** [comment]
autox.js下载地址：https://github.com/kkevsekk1/AutoX/releases

**Comment by Nymph-star** [comment]
> 
刚刚试了一下导进去运行没反应啊 权限无障碍都正常

**Comment by boy5260** [comment]
> > 
> 刚刚试了一下导进去运行没反应啊 权限无障碍都正常

你是用的最新版的autox吗

**Comment by Nymph-star** [comment]
> > > 
> > 
> > 
> > 刚刚试了一下导进去运行没反应啊 权限无障碍都正常
> 
> 你是用的最新版的autox吗

6.1.9版本的最新的

**Comment by boy5260** [comment]
额，我这边确实可以的，你是不是没有导入完全？其实用一个main.js就可以了。

**Comment by Nymph-star** [comment]
> 额，我这边确实可以的，你是不是没有导入完全？其实用一个main.js就可以了。

我导入的main大小为859b

**Comment by youjumenkou** [comment]
确实可以，感谢分享，本来升级到13了，无障碍没法授权又被迫降回去了。今天试了一下确实能用了，感谢！

**Comment by boy5260** [comment]
> > 额，我这边确实可以的，你是不是没有导入完全？其实用一个main.js就可以了。
> 
> 我导入的main大小为859b

我的是760B。你的文件有问题吧
