### ISSUE TITLE
专项答题无限制下滑

### ISSUE THREAD

**Issue by seasky8866** [sec-an/Better-Auto-XXQG#8]
如果专项答题都完成没有可以选，无限制下滑，不像每周答题下滑6次退出。

**Comment by boy5260** [comment]
确实有这个问题。。。有点浪费时间了

**Comment by sec-an** [comment]
专项和每周答题会在第一次运行时判断是否完成先前的全部内容，第一次滑完后会记录一个变量存在本地，下次运行就会根据该变量判断下滑次数。
这两天会增加一个配置，自主选择是否已经完成先前所有答题。

**Comment by seasky8866** [comment]
还有一个问题跳转到本地页面就不会动了，要手动返回才会继续执行后面的

**Comment by youjumenkou** [comment]
还是尽快添加是否完成先前所有答题选项吧，否则首次一直在“查找未作答的专项答题”，最后连刷到2019年的时候基本学习强国都卡死了。

**Comment by youjumenkou** [comment]
卡死在专项答题
